# Generated by Django 5.1.1 on 2024-10-25 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_budget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
