# Generated by Django 5.1.1 on 2024-10-25 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_budget', '0002_alter_manage_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
